config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks do
    post :import, on: :collection
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks_categories, dependent: :destroy
  has_many :tasks, through: :tasks_categories

  validates :title, presence: true

  scope :categories_search, -> (search) { search.present? ? where('title LIKE ?', "%#{search}%") : all }

  def self.ransackable_attributes(auth_object = nil)
    super + ['title']
  end
end

app/models/task.rb
require 'csv'

class Task < ApplicationRecord
  has_many :tasks_categories, dependent: :destroy
  has_many :categories, through: :tasks_categories

  enum :status, { done: 0, doing: 1, not_started: 2 }
  enum :priority, { upper: 0, middle: 1, lower: 2 }

  validates :title, presence: true

  validate :check_deadline_past

  def check_deadline_past
    if deadline_on < Date.today
      errors.add(:deadline_on, 'が本日以前の日付なので登録できません')
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title body deadline_on priority]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[categories]
  end

  def self.import(file)
    error_messages = []

    csv_data = File.read(file.path)
    csv_string = csv_data.gsub("\uFEFF", '')

    csv = CSV.parse(csv_string, headers: true)
    csv.each.with_index(2) do |row, line_number|
      task = Task.find_or_initialize_by(id: row['ID'])
      transformed_attributes = {}
      I18n.with_locale(:en) do
        row.each do
          transformed_attributes = row.to_hash.transform_keys do |key|
            I18n.t("csv.headers.#{key}", default: key)
          end.except('category_titles')
        end

        transformed_attributes['status'] = I18n.t("csv.status.#{row['ステータス']}", default: row['ステータス'])
        transformed_attributes['priority'] = I18n.t("csv.priority.#{row['優先度']}", default: row['優先度'])
      end

      task.attributes = transformed_attributes

      begin
        category_titles = JSON.parse(row['カテゴリー'].split(',').to_json)
        task.categories = Category.where(title: category_titles)
      rescue JSON::ParserError
        error_messages << "#{line_number}行目でエラーが出ています: カテゴリーのJSON解析に失敗しました"
      end

      unless task.save
        error_messages << "#{line_number}行目でエラーが出ています: #{task.errors.full_messages.join(', ')}"
      end
    end

    error_messages
  end
end

app/models/tasks_category.rb
class TasksCategory < ApplicationRecord
  belongs_to :task
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def render_404
    render file: 'public/404.html', status: 404
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.categories_search(params[:search]).page(params[:page])
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice]='カテゴリーの登録が完了しました'
      redirect_to categories_path
    else
      flash.now[:alert]='カテゴリーの登録に失敗しました'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice]='カテゴリーの編集が完了しました'
      redirect_to categories_path
    else
      flash.now[:alert]='カテゴリーの編集に失敗しました'
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if @category.destroy
      flash[:notice]='カテゴリーを削除しました'
      redirect_to categories_path
    else
      flash.now[:notice]='カテゴリーの削除に失敗しました'
      render 'show'
    end
  end

    private
      def category_params
        params.require(:category).permit(:title)
      end

      def set_category
        @category = Category.find(params[:id])
      end
end

app/controllers/tasks_controller.rb
require 'csv'
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result.not_done.page(params[:page])

    respond_to do |format|
      format.html
      format.csv do
        bom = "\uFEFF"
        csv_header = (Task.column_names + ['category_titles'] - ['created_at', 'updated_at']).map do |column|
          t("csv.headers.#{column}", default: column)
        end

        csv_data = CSV.generate(bom) do |csv|
          csv << csv_header

          @tasks.each do |task|
            category_titles = task.categories.pluck(:title).join(',')
            csv << [
              task.id,
              task.title,
              task.body,
              task.deadline_on,
              t("csv.status.#{task.status}", default: task.status),
              t("csv.priority.#{task.priority}", default: task.priority),
              category_titles
            ]
          end
        end

        send_data csv_data, filename: 'tasks.csv', type: 'text/csv'
      end
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = 'タスクの登録が完了しました'
      redirect_to root_path
    else
      flash.now[:alert] = 'タスクの登録に失敗しました'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'タスクの編集が完了しました'
      redirect_to root_path
    else
      flash.now[:alert] = 'タスクの編集に失敗しました'
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = 'タスクを削除しました'
      redirect_to root_path
    else
      flash.now[:alert] = 'タスクを削除できませんでした'
      render 'show'
    end
  end

  def import
    error_messages = Task.import(params[:file])
    if error_messages.any?
      flash[:error] = error_messages.join('\n')
    else
      flash[:success] = 'Import successful.'
    end
    redirect_to root_path
  end

    private
      def task_params
        params.require(:task).permit(:title, :body, :deadline_on, :status, :priority, category_ids: [])
      end

      def set_task
        @task = Task.find(params[:id])
      end
end

app/views/categories/_form.html.erb
<%= flash.now[:alert] %>

<%= form_with model: @category, local: true do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
  <p><%= form.label :title %><br>
    <%= form.text_field :title %> 
  </p>

  <%= form.submit %> 
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<%= link_to 'カテゴリー登録', new_category_path %>
<%= flash[:notice]%>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to(category.title, category_path(category)) %></li>
  <% end %>    
</ul> 
<%= paginate @categories %>   
<p>カテゴリー検索</p>
<%= form_with url: categories_path, method: :get, local: true do |form| %>
  <%= form.text_field :search %>
  <%= form.submit '検索' %>
<% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<ul>
  <li><%= @category.title %></li>
</ul>
<%= link_to '編集', edit_category_path %>
<%= button_to '削除', category_path, method: :delete %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul style="color: red">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_error_messages.html.erb
<% if @task.errors.any? %>
  <div>
    <ul style="color: red">
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= flash.now[:alert] %>

<%= form_with model: @task, local: true do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
  <p><%= form.label :title %><br>
    <%= form.text_field :title %> 
  </p>

  <p><%= form.label :body %><br>
    <%= form.text_area :body %> 
  </p>

  <p><%= form.label :category_ids, 'カテゴリー' %><br>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :title do |cb| %>
      <%= cb.check_box %>
      <%= cb.label %>
    <% end %>
  </p>  

  <%= form.label :deadline_on, '終了期限' %><br>
  <%= form.date_field :deadline_on %><br>

  <%= form.label :status, 'ステータス' %><br>
  <%= form.select :status, Task.statuses.keys.to_a.map  { |p| [Task.statuses_i18n[p], p] } %><br>

  <%= form.label :priority, '優先順位' %><br>
  <%= form.select :priority, Task.priorities.keys.to_a.map { |p| [Task.priorities_i18n[p], p] } %><br>

  <%= form.submit %> 
<% end %>

app/views/tasks/_form_task.html.erb
<%= flash.now[:alert] %>

<%= form_with model: @task, local: true do |form| %>
    <%= render 'layouts/error_messages' %>
    <p><%= form.label :title %><br>
    <%= form.text_field :title %> 
    </p>

    <p><%= form.label :body %><br>
    <%= form.text_area :body %> 
    </p>

    <%= form.submit %> 
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<%= link_to 'カテゴリー一覧', categories_path %>
<%= link_to '新規投稿', new_task_path %>
<%= flash[:notice] %>
<%= flash[:success] %>
<%= flash[:error] %>
<ul>
  <%= sort_link(@q, :deadline_on, "終了期限" )%>
  <%= sort_link(@q, :priority, "優先順位" )%>
  <% @tasks.each do |task| %>
    <li><%= link_to(task.title, task_path(task)) %></li>
  <% end %>    
</ul>    
<%= paginate @tasks %>
<p>タスク検索</p>
<%= search_form_for @q do |f| %>
  <%= f.label :title_cont, 'タイトル' %>
  <%= f.search_field :title_cont %><br>

  <%= f.label :body_cont, '説明文' %>
  <%= f.search_field :body_cont %><br>
  
  <%= f.label :categories_title_cont, 'カテゴリー' %>
  <%= f.collection_select :categories_title_cont, Category.all, :title, :title, include_blank: true %>

  <%= f.submit '検索' %>
<% end %>

<%= link_to "csvで出力する", tasks_path(format: :csv) %>
<%= form_tag import_tasks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<ul>
  <li><%= @task.title %></li>
  <li><%= @task.body %></li>
  <li><%= @task.deadline_on.strftime('%Y年 %m月 %d日') %></li>
  <li><%= @task.status_i18n %></li>
  <li><%= @task.priority_i18n %></li>
</ul>  
<p>選択したカテゴリー</p>
<ul>
  <% @task.categories.each do |category| %>
    <li><%= category.title %></li>
  <% end %>
</ul>  

<%= link_to '編集', edit_task_path %>
<%= button_to '削除', task_path, method: :delete %>